NAS: https://mydomain.synology.me:6121
mapping:
  grafana.mydomain.synology.me:
    host: http://192.168.0.16:3000
    endpoint: ''
    method: GET
  homeassistant.mydomain.synology.me:
    host: http://192.168.0.15:8213
    endpoint: example
    method: GET
